name: Check Commits

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  commitlint:
    name: Check Commits
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Install environment
        run: nix develop --command pnpm i

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: nix develop --command cli check-commits --from HEAD~1 --to HEAD

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: nix develop --command cli check-commits --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }}
