name: Deploy Documentation Site

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build docs site
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Install environment
        run: nix-shell --run "pnpm i"

      - name: Test
        run: nix-shell --run "cli build-docs"

      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/"

  deploy:
    name: Deploy docs site
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
