name: Test Code

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Install environment
        run: nix develop --command pnpm i

      - name: Test
        run: nix develop --command cli test
